services:
  chatsite_db:
    image: postgres:15
    container_name: chatsite-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../db:/var/lib/postgresql/data
    networks:
      - xyz

  chatsite:
    build: .
    container_name: chatsite
    user: "1000:1000"
    volumes:
      - ./media:/app/media
      - ./staticcollection:/app/staticcollection
    expose:
      - "8999"
    depends_on:
      - chatsite_db
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - xyz

networks:
  xyz:
    external: true